default_language_version:
  python: python3

default_stages: [commit, manual]

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: trailing-whitespace
        exclude: ^.*\.md$
      - id: end-of-file-fixer
      - id: check-yaml
        args: [--allow-multiple-documents]

  - repo: https://github.com/PyCQA/isort
    rev: 5.7.0
    hooks:
      - id: isort
        args: [ --line-width=120, --ignore-whitespace ]

#  - repo: https://github.com/pycqa/pylint
#    rev: pylint-2.4.4
#    hooks:
#      - id: pylint
#        exclude: ^(test|docs).*$

  - repo: https://github.com/ambv/black
    rev: 19.3b0
    hooks:
      - id: black
